module harmony_heart::heart {
    use sui::object::{Self, UID, ID};
    use sui::tx_context::{Self, TxContext};
    use sui::transfer;
    use std::string::{Self, String};
    use sui::event;

    /// Errors
    const ENotOwner: u64 = 0;

    /// The MarketVault represents a programmable dWallet ('Omni-Heart') 
    /// that can natively control assets on other chains (Solana, BTC, ETH, etc.)
    /// following the Ika & Encrypt primitives.
    struct MarketVault has key, store {
        id: UID,
        owner: address,
        target_chain: String,      // e.g., "Solana", "Bitcoin"
        dwallet_id: vector<u8>,    // The Ika dWallet ID
        dwallet_pubkey: vector<u8>, // The public key generated by Ika DKG
        encrypted_state: vector<u8>, // Encrypted execution data for private logic (Encrypt)
        status: String,            // Current state (e.g., "INITIALIZED", "APPROVED")
    }

    /// Event emitted when a message is approved for Ika signing
    struct MessageApproved has copy, drop {
        vault_id: ID,
        message_hash: vector<u8>,
        target_chain: String,
    }

    /// Initialize a new Market Vault (Bridgeless Capital Primitive)
    public entry fun create_vault(
        target_chain: vector<u8>,
        dwallet_id: vector<u8>,
        dwallet_pubkey: vector<u8>,
        encrypted_state: vector<u8>,
        ctx: &mut TxContext
    ) {
        let vault = MarketVault {
            id: object::new(ctx),
            owner: tx_context::sender(ctx),
            target_chain: string::utf8(target_chain),
            dwallet_id,
            dwallet_pubkey,
            encrypted_state,
            status: string::utf8(b"INITIALIZED"),
        };
        transfer::public_transfer(vault, tx_context::sender(ctx));
    }

    /// Approve a message for signing (Ika 2PC-MPC Flow)
    /// This is the core "Bridgeless" action.
    public entry fun approve_message(
        vault: &mut MarketVault,
        message_hash: vector<u8>,
        ctx: &mut TxContext
    ) {
        assert!(vault.owner == tx_context::sender(ctx), ENotOwner);
        
        vault.status = string::utf8(b"MESSAGE_APPROVED");
        
        event::emit(MessageApproved {
            vault_id: object::uid_to_inner(&vault.id),
            message_hash,
            target_chain: vault.target_chain,
        });
    }

    /// Update the encrypted state (Encrypt Private Execution)
    /// This allows the vault to maintain private market data.
    public entry fun update_private_state(
        vault: &mut MarketVault,
        new_encrypted_state: vector<u8>,
        ctx: &mut TxContext
    ) {
        assert!(vault.owner == tx_context::sender(ctx), ENotOwner);
        
        vault.encrypted_state = new_encrypted_state;
        vault.status = string::utf8(b"STATE_UPDATED");
    }

    /// Transfer ownership of the vault (e.g., to a DAO or another program)
    public entry fun transfer_vault(
        vault: MarketVault,
        recipient: address,
        _ctx: &mut TxContext
    ) {
        transfer::public_transfer(vault, recipient);
    }
}
